stages:
  - test
  - build
  - publish
  - sync

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-commits-signoffs.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-docker-build.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-docker-deploy.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'

test:check-python3-formatting:
  stage: test
  needs: []
  image: python:3
  before_script:
    - pip install tox
  script:
    - TOXENV=flake8 tox

test:acceptance-tests:
  stage: test
  needs: []
  tags:
    - docker
  image: tiangolo/docker-with-compose
  services:
    - docker:19.03.5-dind
  before_script:
    - apk add py3-tox bash
    - docker --version
    - docker-compose --version
    # TODO: rework to not build here and test pre-built images
    - make docker-build
    - make docker-deploy
    - sleep 5
    - make docker-port || true
    - docker-compose -f docker-compose.yml logs
  script:
    - cp etc/tetra/tetra-test.conf.sample tetra-test.conf
    - TOXENV=functional tox

build:docker:
  variables:
    DOCKER_REPOSITORY: mendersoftware/mantra-api
  only:
    changes:
      - tetra/**/*
      - setup.py
      - etc/tetra/tetra.conf.sample
      - Dockerfile

publish:image:
  variables:
    DOCKER_REPOSITORY: mendersoftware/mantra-api
  only:
    changes:
      - tetra/**/*
      - setup.py
      - etc/tetra/tetra.conf.sample
      - Dockerfile

sync:image:
  variables:
    DOCKER_REPOSITORY: mendersoftware/mantra-api
    TARGET_MANIFEST_FILE: "kubernetes/qastatus/api-deployment.yaml,kubernetes/qastatus/worker-deployment.yaml"
  only:
    changes:
      - tetra/**/*
      - setup.py
      - etc/tetra/tetra.conf.sample
      - Dockerfile

build:docker:ui:
  extends: build:docker
  variables:
    DOCKER_REPOSITORY: mendersoftware/mantra-ui
    DOCKER_DIR: ui
  only:
    changes:
      - ui/**/*

publish:image:ui:
  extends: publish:image
  dependencies:
    - build:docker:ui
  variables:
    DOCKER_REPOSITORY: mendersoftware/mantra-ui
    DOCKER_DIR: ui
  only:
    changes:
      - ui/**/*

sync:image:ui:
  extends: sync:image
  dependencies:
    - publish:image:ui
  variables:
    DOCKER_REPOSITORY: mendersoftware/mantra-ui
    TARGET_MANIFEST_FILE: kubernetes/qastatus/ui-deployment.yaml
  only:
    changes:
      - ui/**/*
